version: "3.9"
services:
  dataportal-backend:
    build:
      context: ../dataportal
      dockerfile: backend/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - "dataportal-db"
    volumes:
      - ../dataportal/backend/src:/app/src
      - ../dataportal/shared:/shared
    environment:
      NODE_ENV: docker
    command: ["scripts/wait-for-it.sh", "dataportal-db:5432", "-t", "120", "--", "npm", "run", "start-dev"]
  dataportal-backend-test:
    build:
      context: ../dataportal
      dockerfile: backend/Dockerfile
      target: dev
    ports:
      - "3001:3001"
    depends_on:
      - "dataportal-db"
    volumes:
      - ../dataportal/backend/src:/app/src
      - ../dataportal/backend/tests:/app/tests
      - ../dataportal/shared:/shared
    environment:
      NODE_ENV: docker-test
    command: ["scripts/wait-for-it.sh", "dataportal-db:5432", "-t", "120", "--", "npm", "run", "start-test"]
  dataportal-db:
    image: "postgres:13"
    user: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "54321:5432"
    environment:
      TZ: "Europe/Helsinki"
      POSTGRES_DB: dataportal
      POSTGRES_USER: dataportal
      POSTGRES_PASSWORD: dev
  dataportal-frontend:
    build:
      context: ../dataportal
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - ../dataportal/frontend/src:/app/src
      - ../dataportal/backend/src/entity:/backend/src/entity
    ports:
      - "8080:8080"
    depends_on:
      - "dataportal-backend"
    command: ["npm", "run", "serve"]
  moto-server:
    image: "motoserver/moto"
