version: "3.9"
services:
  dataportal-backend:
    image: dataportal-backend
    pull_policy: never
    build:
      context: ../dataportal
      dockerfile: backend/Dockerfile
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../dataportal/backend/src:/app/src
      - ../dataportal/shared:/shared
      - ../dataportal-resources:/dataportal-resources
    env_file:
      - ../dataportal/backend/dev.env
    command: ["npm", "run", "start-dev"]
  dataportal-backend-test:
    image: dataportal-backend
    pull_policy: never
    ports:
      - "3001:3000"
      - "5921:5920"
    depends_on:
      db:
        condition: service_healthy
      dataportal-backend:
        condition: service_started
    volumes:
      - ../dataportal/backend/src:/app/src
      - ../dataportal/backend/tests:/app/tests
      - ../dataportal/shared:/shared
    env_file:
      - ../dataportal/backend/test.env
    command: ["npm", "run", "start-test"]
  db:
    image: "postgres:13"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "54321:5432"
    environment:
      TZ: "Europe/Helsinki"
      POSTGRES_DB: $PGDATABASE
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      PGUSER: ss
    healthcheck:
     test: ["CMD", "psql", "-c", "select 1"]
     interval: 1s
     retries: 120
  dataportal-frontend:
    build:
      context: ../dataportal
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - ../dataportal/frontend/src:/app/src
      - ../dataportal/backend/src/entity:/backend/src/entity
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_BACKENDURL=http://localhost:3000/api/
    command: ["npm", "run", "serve"]
  moto-server:
    image: "motoserver/moto"
  storage-service:
    build:
      context: ../storage-service
      target: dev
    ports:
      - "5900:5900"
    depends_on:
      db:
        condition: service_healthy
      moto-server:
        condition: service_started
    volumes:
      - ../storage-service/src:/app/src
    environment:
      - SS_MODE
      - PGUSER=ss
      - PGPASSWORD
      - PGHOST
      - PGDATABASE=ss
    command: ["npm", "run", "start-dev"]
  pid-service:
    build: ../pid-service
    ports:
      - "5800:5800"
  data-processing:
    build: ../data-processing
    depends_on:
      - "dataportal-backend"
      - "storage-service"
      - "pid-service"
    volumes:
      - ../data-processing/scripts:/app/scripts
      - ../data-processing/src:/app/src
      - ../data-processing/tests:/app/tests
    env_file:
      - ../data-processing/dev.env
